env:
  global:
    - PINS="usane:https://github.com/hannesm/usane.git cs:https://github.com/cfcs/ocaml-cs.git mirage:https://github.com/cfcs/mirage.git#fix_qubes mirage-xen:https://github.com/cfcs/mirage-platform.git#virt_to_mfn mirage-qubes:https://github.com/cfcs/mirage-qubes.git#guid_mvar mirage-framebuffer:https://github.com/cfcs/mirage-framebuffer.git mirage-framebuffer-tsdl:https://github.com/cfcs/mirage-framebuffer.git mirage-framebuffer-qubes:https://github.com/cfcs/mirage-framebuffer.git rfc6287:https://github.com/sg2342/ocaml-rfc6287.git#master nocrypto:https://github.com/mirleft/ocaml-nocrypto.git#79d5db2488e338d161d7e170cd681a8120ce07d1"
    - PACKAGE="mirage-ocra-demo"
    - FLAGS="--suite OCRA-1:HOTP-SHA1-6:C-QN08-PSHA1 --card_secret bb3508569b89cdbabb7e5bea39cf09162dfe9c91"

matrix:
  include:
    - os: osx
      env: MIRAGE_BACKEND=macosx OCAML_VERSION=4.06
    - os: linux
      env: MIRAGE_BACKEND=unix OCAML_VERSION=4.04
      #- os: linux
      #env: MIRAGE_BACKEND=unix OCAML_VERSION=4.05
      #- os: linux
      #env: MIRAGE_BACKEND=unix OCAML_VERSION=4.06
    - os: linux
      env: MIRAGE_BACKEND=xen OCAML_VERSION=4.04
    - os: linux
      env: MIRAGE_BACKEND=xen OCAML_VERSION=4.05
    - os: linux
      env: MIRAGE_BACKEND=xen OCAML_VERSION=4.06

language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-mirage.sh
sudo: required
script: bash -ex .travis-mirage.sh
branches:
  only:
    - gh-pages
    - /.*/
git:
  depth: 2
notifications:
  email: false
